### ISSUE TITLE
Merge with dotify.api

### ISSUE THREAD

**Issue by joeha480** [brailleapps/braille-utils.api#3]
This api should probably be merged with dotify.api (but perhaps it too should subsequently be renamed). The reason for this is that there is not enough distinction between the apis to motivate separate packages considering project overhead and team size. Also, bringing these apis together might benefit the development of this api as it is currently somewhat behind in code style etc.

Things to do before merging:
- [x] APIs that are not fit for this new location should be deprecated, namely the validator interface (#2)
- [x] All projects that depend on this should be prepared to be updated to Java 8 (as they will have to use Java 8 once they start using the new api) (brailleapps/issues#9)
- [x] Release a minor/service version (because some things have been deprecated since the last release)
- [x] Rename README.md to readme.md (or do the merge on Linux, or change readme.md in dotify.api to README.md)
- [x] Release a clean major version (see #8)
- [x] Fix #9
- [x] Add a notice that the API has been deprecated (see for example dotify.task-api)
- [x] Release a final version

**Comment by joeha480** [comment]
Done!
